version: '3.7'

services:
  apache:
    build: './apache'
    restart: always
    ports:
      - 80:80
      # - 443:443
    networks: 
      - frontend
      - backend
    volumes:
      - ~/Project/web:/usr/local/apache2/htdocs
      - ./cert/:/usr/local/apache2/cert/
      - ./apache/logs:/var/log/apache
    depends_on:
      - php
      - db
  php:
    build: './php'
    restart: always
    networks: 
      - backend
    volumes:
      - ~/Project/web:/usr/local/apache2/htdocs
      - ./tmp:/usr/local/tmp
    depends_on:
      - db
  db:
    build: './mysql'
    restart: always
    networks:
      - backend
    volumes:
      - ./database:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    restart: always
    ports:
     - 8011:80
    environment:
      PMA_HOST: db
    volumes:
      - ./phpmyadmin:/var/www/phpmyadmin
    networks: 
      - backend
    depends_on:
      - db

networks: 
  backend:
  frontend:
